// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrJeLMAYdy6opo86g4sJbA8kW7xW32b4',
    appId: '1:36215335171:web:36c5d4234c515fb83aa136',
    messagingSenderId: '36215335171',
    projectId: 'kampus-gratis2',
    authDomain: 'kampus-gratis2.firebaseapp.com',
    databaseURL:
        'https://kampus-gratis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampus-gratis2.appspot.com',
    measurementId: 'G-M4QT5PH0HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xMlk09-Skzzr-Jt77ZQEFPYSX8VcsLw',
    appId: '1:36215335171:android:96254011eddfc9593aa136',
    messagingSenderId: '36215335171',
    projectId: 'kampus-gratis2',
    databaseURL:
        'https://kampus-gratis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampus-gratis2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZZt1NknQsTB72hpZEGbOkHHX2TiPogk',
    appId: '1:36215335171:ios:d66e98d8ac854c643aa136',
    messagingSenderId: '36215335171',
    projectId: 'kampus-gratis2',
    databaseURL:
        'https://kampus-gratis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampus-gratis2.appspot.com',
    androidClientId:
        '36215335171-24qf8klfegt7cdtmoosg04ndtl1bjc3j.apps.googleusercontent.com',
    iosClientId:
        '36215335171-n8h12q03dfmq0o9bqu07b424h4uspkm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kampusGratis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZZt1NknQsTB72hpZEGbOkHHX2TiPogk',
    appId: '1:36215335171:ios:d66e98d8ac854c643aa136',
    messagingSenderId: '36215335171',
    projectId: 'kampus-gratis2',
    databaseURL:
        'https://kampus-gratis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampus-gratis2.appspot.com',
    androidClientId:
        '36215335171-24qf8klfegt7cdtmoosg04ndtl1bjc3j.apps.googleusercontent.com',
    iosClientId:
        '36215335171-n8h12q03dfmq0o9bqu07b424h4uspkm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kampusGratis',
  );
}
